modLoader="javafml"
loaderVersion="[32,)"
logoFile="logo.png"
authors="Ropoocha"

[[mods]]
modId="moddilities"
varsion="${file.jarVersion}"
displayName="Moddilities"
description='''
Various utilities for varius mods!'''

[[dependencies.moddilities]]
modId="forge"
mandatory=true
versionRange="[32,)"
ordering="NONE"
side="BOTH"